steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/book-scan-quizz:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/book-scan-quizz:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'book-scan-quizz'
    - '--image'
    - 'gcr.io/$PROJECT_ID/book-scan-quizz:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--update-env-vars'
    - |
      FLASK_CONFIG=testing,
      GOOGLE_CLIENT_ID=792066325521-dgtt0c4cp36nace09o3fcslflh9m4s4h.apps.googleusercontent.com
# Use the custom service account
serviceAccount: 'cloudbuild-deploy-account@earn-your-screentime.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY